channels:
  - conda-forge
dependencies:
  - firefox
  - geckodriver
  - selenium
  - fuzzywuzzy
  - pyngrok
  - lxml
  - semanticscholar
  - rdflib
  - owlrl
  - sparqlwrapper
  - streamlit
  - texthero
  - requests
  - bs4
